sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "8"
  - "9"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

script:
  - npm run finish

after_success:
  - codeclimate-test-reporter < ./test/unit/coverage/lcov.info
