os:
  - linux

sudo: false

language: node_js

node_js:
  - "6"

install:
  - npm install
  - npm update

script:
  - npm run unit
  - npm run bundle
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)
