os:
  - linux

sudo: false

language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

install:
  - npm install
  - npm update

script:
  - npm run unit
  - npm run bundle
  - npm run build
  - eslint --ext .js,.vue src test/e2e/specs

after_success:
  - bash <(curl -s https://codecov.io/bash)
